### ISSUE TITLE
Is it possible to create Angular frontend App linking with Payme payment?

### ISSUE THREAD

**Issue by JeongJun-Lee** [PaycomUZ/AndroidSDK#6]
Hello, I came here from https://help.paycom.uz/. I am creating a hybrid app by Angular on Web layer. Do you have an example for Angular? I only found [plugin examples](https://help.paycom.uz/ru/plaginy-dlya-cms) for PHP based CMS there. Is it possible to create Angular frontend App linking with Payme payment without backend side implementation? Thanks.

**Comment by N-i-p-o-l** [comment]
Hi. Please contact via business.payme.uz. This repository only for issues in Android SDK

**Comment by JeongJun-Lee** [comment]
I really really want to contact to business.payme.uz. But I can't communicate them in English on the phone. Also I already emailed them my questions in English. But no answers. Sorry the reason I am writing here. So if possible, I want to get the answer from you. Do I always need my own [backend server](https://github.com/PaycomUZ/paycom-integration-java-template) for payment by payme? Is it possible to pay by only frontend app like angular or android without my own backend?

**Comment by N-i-p-o-l** [comment]
Yes, you need your own backend for cashbox types with billing. But you can use cashbox without billing type (usually used for business card site)

**Comment by JeongJun-Lee** [comment]
OK. thank you for your reply.
